### ISSUE TITLE
[Feature] 누구테스트 페이지 UI를 구현한다.  

### ISSUE THREAD

**Issue by Chaem03** [Line4Thon-Nugu/Nugu-Frontend#15]
## ✔️ Issue
>누구테스트 페이지 UI를 구현한다.
## 📝 To-do

- [x] (소유자뷰,접속자뷰 공통) 테스트 X UI구현
- [x] 테스트 순위 컴포넌트 제작
- [x] 소유자뷰 누구테스트 페이지 UI구현 (정답 배열로 담기) 

## 🛠 Working time

>1D
