### ISSUE TITLE
[Feature] 누구 접속자 / 소유자 UI 및 작동 로직을 구현한다.

### ISSUE THREAD

**Issue by sayyyho** [Line4Thon-Nugu/Nugu-Frontend#16]
## ✔️ Issue

누구 접속자 / 소유자 UI 및 기본 작동 로직을 구현합니다.

## 📝 To-do

- [ ] 토큰에 따른 라우팅 처리
- [ ] UUID를 통한 사용자 식별
- [ ] 복사 / 공유 로직 부여
- [x] UI 구현

## 🛠 Working time

- 1d
