### ISSUE TITLE
[Chore]- 접속자/소유자뷰에 따른 누구테스트  경로 수정 

### ISSUE THREAD

**Issue by Chaem03** [Line4Thon-Nugu/Nugu-Frontend#20]
## ✔️ Issue
>접속자/소유자뷰에 따른 누구테스트  경로 수정
## 📝 To-do

- [ ] 접속자 뷰 누구테스트 경로 테스트
- [ ] 소유자 뷰 누구테스트 경로 테스트
- [ ] 누구 소개 빈 배열 여부에 따라 화면 다르게 되도록 로직 수정

## 🛠 Working time

>3H
