### ISSUE TITLE
[Feature] 누구 접속자 / 소유자 작동 로직을 구현한다.

### ISSUE THREAD

**Issue by sayyyho** [Line4Thon-Nugu/Nugu-Frontend#33]
## ✔️ Issue

- 누구 페이지에서 서버와 API 연결 이후, 소유자 / 접속자 검증 로직을 구현합니다.
- 소유자는 누구를 공유할 수 있도록 구현합니다.

## 📝 To-do

- [x] 소유자 누구 조회 API 연동
- [x] 소유자 UUID를 통한 API 연동 및 링크 공유
- [x] 접속자 UUID를 통한 API 연동

## 🛠 Working time

3h
