### ISSUE TITLE
[Design] 로그인/온보딩/누구소개/누구수정 UI 수정 및 누구 테스트 API 연동

### ISSUE THREAD

**Issue by Chaem03** [Line4Thon-Nugu/Nugu-Frontend#66]
## ✔️ Issue
>로그인/온보딩/누구소개/누구수정 UI 수정
## 📝 To-do

- [x] 로그인/온보딩 Botton padding
- [x] 누구 소개-Botton padding
- [x] 누구 수정 - 버튼 간격수정, 인스타 아이디 get 해 올 경우 아이디만 가져오기
- [ ] QA하면서 생기는 UI 수정
- [ ] 누구테스트  소유자 답변 get 연결
- [ ] 누구테스트 완료 시 넘어가는 완료 페이지에서 상위 3개의 랭킹만 보이게 수정

## 🛠 Working time
>1D
